# Generated by Django 4.1.4 on 2022-12-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='opciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=150, null=True, verbose_name='Palabra clave para dar una respuesta')),
                ('respuest', models.CharField(max_length=500, null=True, verbose_name='Respuesta que dará el Chatbot')),
            ],
            options={
                'db_table': 'opciones',
            },
        ),
    ]
