# Generated by Django 4.1.1 on 2022-12-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0002_opciones_nameproyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opciones',
            name='nameproyecto',
        ),
        migrations.AddField(
            model_name='opciones',
            name='descripcion',
            field=models.CharField(max_length=50, null=True, verbose_name='NOmbre proyecto'),
        ),
    ]
