# Generated by Django 4.1.1 on 2022-12-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0003_remove_opciones_nameproyecto_opciones_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opciones',
            name='descripcion',
            field=models.CharField(max_length=200, null=True, verbose_name='Descripción de lo que hara la clave'),
        ),
    ]
